### ISSUE TITLE
Group and Resource comments are not recognized by fluent backend

### ISSUE THREAD

**Issue by JonL1** [i18next/i18next-fluent-backend#1]
## 🐛 Bug Report

Group(##) and Resource(###) comments are not serialized by the fluent backend. Standalone ones(#) are parsed correctly.

Console error in debug mode: 

![image](https://user-images.githubusercontent.com/1325712/144760465-7cfc8145-8e8b-4153-8841-37d959e14ce6.png)

## To Reproduce

Using the comment example from project fluent ends up in an error.
https://projectfluent.org/fluent/guide/comments.html

## Expected behavior

A file with comments should be parsed correctly by the fluent backend.

## Your Environment

- *runtime version*: browser(all)
- *i18next version*: 21.5.2
- *i18nextFluent version*: 1.0.1
- *i18nextFluentBackend version*: 0.0.2
- *os*: Mac

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this?

**Comment by JonL1** [comment]
I can try. I just need some indications.

The issue is that the functions `getResourceComment` and `getGroupComment` are not defined. 

I can see the key for standalone comments is just `comment`. What keys should I use for resource and group comments?

Also when a standalone comment is bound to a translation string it will generate an object.

![image](https://user-images.githubusercontent.com/1325712/144762025-b4cc94c7-d0b5-4731-9ba1-10be196d26cf.png)

I'm assuming this is not needed for group and resource as they will always be standalone comments.

Although group comments do separate sections so I don't know if all the translation strings belonging to a group comment should be added to the same object

**Comment by jamuhl** [comment]
Comments aren't needed at all and not supported in i18next. So ignoring those while parsing would be the best solution - just not throwing an error...
